# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.deep_pb2 as deep__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in deep_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeepSrvStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTwoNum = channel.unary_unary(
                '/deep.DeepSrv/AddTwoNum',
                request_serializer=deep__pb2.NumReq.SerializeToString,
                response_deserializer=deep__pb2.NumResp.FromString,
                _registered_method=True)
        self.AddAllTheseNum = channel.stream_unary(
                '/deep.DeepSrv/AddAllTheseNum',
                request_serializer=deep__pb2.Num.SerializeToString,
                response_deserializer=deep__pb2.NumResp.FromString,
                _registered_method=True)


class DeepSrvServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTwoNum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAllTheseNum(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeepSrvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTwoNum': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTwoNum,
                    request_deserializer=deep__pb2.NumReq.FromString,
                    response_serializer=deep__pb2.NumResp.SerializeToString,
            ),
            'AddAllTheseNum': grpc.stream_unary_rpc_method_handler(
                    servicer.AddAllTheseNum,
                    request_deserializer=deep__pb2.Num.FromString,
                    response_serializer=deep__pb2.NumResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deep.DeepSrv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('deep.DeepSrv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeepSrv(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTwoNum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deep.DeepSrv/AddTwoNum',
            deep__pb2.NumReq.SerializeToString,
            deep__pb2.NumResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAllTheseNum(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/deep.DeepSrv/AddAllTheseNum',
            deep__pb2.Num.SerializeToString,
            deep__pb2.NumResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
