# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deep.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'deep.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndeep.proto\x12\x04\x64\x65\x65p\"\x1e\n\x06NumReq\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x10\n\x03Num\x12\t\n\x01\x61\x18\x01 \x01(\x05\"\x14\n\x07NumResp\x12\t\n\x01\x63\x18\x01 \x01(\x05\x32\x61\n\x07\x44\x65\x65pSrv\x12(\n\tAddTwoNum\x12\x0c.deep.NumReq\x1a\r.deep.NumResp\x12,\n\x0e\x41\x64\x64\x41llTheseNum\x12\t.deep.Num\x1a\r.deep.NumResp(\x01\x42\x10Z\x0e./server/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deep_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016./server/proto'
  _globals['_NUMREQ']._serialized_start=20
  _globals['_NUMREQ']._serialized_end=50
  _globals['_NUM']._serialized_start=52
  _globals['_NUM']._serialized_end=68
  _globals['_NUMRESP']._serialized_start=70
  _globals['_NUMRESP']._serialized_end=90
  _globals['_DEEPSRV']._serialized_start=92
  _globals['_DEEPSRV']._serialized_end=189
# @@protoc_insertion_point(module_scope)
